In [1]:
import numpy as np
import pandas as pd

# Load DataSet

In [2]:
ihcd = pd.read_csv('insurance.csv')

# Data Analysis Life Cycle

In [3]:
np.unique(ihcd['region'])

array(['northeast', 'northwest', 'southeast', 'southwest'], dtype=object)

In [4]:
np.unique(ihcd['sex'])

array(['female', 'male'], dtype=object)

In [5]:
np.unique(ihcd['age'])

array([18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64])

In [6]:
np.unique(ihcd['children'])

array([0, 1, 2, 3, 4, 5])

In [7]:
np.unique(ihcd['bmi'])

array([15.96 , 16.815, 17.195, 17.29 , 17.385, 17.4  , 17.48 , 17.67 ,
       17.765, 17.8  , 17.86 , 17.955, 18.05 , 18.3  , 18.335, 18.5  ,
       18.6  , 18.715, 18.905, 19.   , 19.095, 19.19 , 19.3  , 19.475,
       19.57 , 19.8  , 19.855, 19.95 , 20.045, 20.1  , 20.13 , 20.235,
       20.3  , 20.35 , 20.4  , 20.425, 20.52 , 20.6  , 20.615, 20.7  ,
       20.79 , 20.8  , 20.9  , 21.01 , 21.09 , 21.12 , 21.28 , 21.3  ,
       21.375, 21.4  , 21.47 , 21.5  , 21.56 , 21.565, 21.66 , 21.7  ,
       21.755, 21.78 , 21.8  , 21.85 , 21.89 , 21.945, 22.   , 22.04 ,
       22.1  , 22.135, 22.22 , 22.23 , 22.3  , 22.42 , 22.515, 22.6  ,
       22.61 , 22.705, 22.77 , 22.8  , 22.88 , 22.895, 22.99 , 23.   ,
       23.085, 23.1  , 23.18 , 23.2  , 23.21 , 23.275, 23.3  , 23.32 ,
       23.37 , 23.4  , 23.465, 23.54 , 23.56 , 23.6  , 23.65 , 23.655,
       23.7  , 23.75 , 23.76 , 23.8  , 23.845, 23.87 , 23.9  , 23.94 ,
       23.98 , 24.035, 24.09 , 24.1  , 24.13 , 24.225, 24.3  , 24.31 ,
      

In [8]:
## Clean DataSet
nan_ihcd = ihcd[ihcd.isna().any(axis=1)]
display(nan_ihcd.head())

Empty DataFrame
Columns: [age, sex, bmi, children, smoker, region, charges]
Index: []

In [9]:
## Get an approximate average
ihcd.describe()

age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [10]:
ihcd[ihcd['region'] == 'southwest']['charges'].mean()

12346.937377292308

In [11]:
ihcd[ihcd['region'] == 'northwest']['charges'].mean()

12417.57537396923

In [12]:
ihcd[ihcd['region'] == 'southeast']['charges'].mean()

14735.411437609888

In [13]:
ihcd[ihcd['region'] == 'northeast']['charges'].mean()

13406.384516385804

In [14]:
ihcd[(ihcd['region'] == 'southwest') & (ihcd['smoker']=='yes')]['charges'].mean()


32269.06349362069

In [15]:
ihcd[(ihcd['region'] == 'southwest') & (ihcd['smoker']=='no')]['charges'].mean()


8019.28451307116

In [16]:
ihcd[(ihcd['region'] == 'southwest') & (ihcd['smoker']=='yes')&(ihcd['children']>2)]['charges'].mean()



23154.002

# Prepare the data